using bem methodologies for classname
Obi1kan/ebs-intership pull request #12
Opened 2023-03-23 10:19 UTC by Obi1kan

2023-03-23 15:06 UTC, H7GhosT requested changes

2023-03-23 15:06 UTC, H7GhosT commented on packages/user-interface/src/components/ErrorPage/ErrorPage.tsx
> +        src={require('./images/error-image.jpg')}
Use import not require
`import errorImgSrc from "....jpg"`

2023-03-23 15:06 UTC, H7GhosT commented on packages/user-interface/src/App.tsx
> +import Homepage from './pages/Homepage';
Be consistent with default and named exports

2023-03-23 15:06 UTC, H7GhosT commented on packages/user-interface/src/components/SignUp.tsx
>        />
Create component for input, so you don't have to duplicate your styles

2023-03-23 15:16 UTC, GribinetDaniel commented on packages/user-interface/src/components/ErrorPage/ErrorPage.tsx
> +        src={require('./images/error-image.jpg')}
La mine nu merge cu import, din cauza asta si i-am data require

2023-03-24 15:33 UTC, H7GhosT requested changes

2023-03-24 15:33 UTC, H7GhosT commented on packages/user-interface/src/types/inputProps.tsx
> +export interface InputProps {
Place the InputProps right in the file of the component

2023-03-24 15:54 UTC, merged