Add functionality to edit/delete post on separate page
Obi1kan/ebs-intership pull request #16
Opened 2023-04-07 13:50 UTC by Obi1kan

2023-04-18 06:20 UTC, H7GhosT requested changes

2023-04-18 06:20 UTC, H7GhosT commented on packages/user-interface/src/components/DeletePostModal/DeletePostModal.tsx
> +        <button
Create a component for button, and control whether it's type is 'primary' or 'secondary' through it's props

2023-04-20 10:04 UTC, H7GhosT requested changes

2023-04-20 10:04 UTC, H7GhosT commented on packages/user-interface/src/pages/EditPost/EditPost.tsx
> +    `edit-post`,
Try to edit one post, then right after that go to edit another post and see what happens
Do not refresh the page while doint this

2023-04-20 10:04 UTC, H7GhosT commented on packages/user-interface/src/pages/EditPost/EditPost.tsx
> +      await mainAxios.patch(`${path}`, post);
Use mutations here and set loading to action buttons

2023-04-20 10:04 UTC, H7GhosT commented on packages/user-interface/src/pages/Register/Register.tsx
> +          let errs: Array<{ msg: string; param: string }> = [];
Create an util for extracting error messages

2023-04-20 10:04 UTC, H7GhosT commented on packages/user-interface/src/components/Button/Button.tsx
> +  text: string;
You can pass a `children` prop and that will get the elements passed here <Button>{children}</Button>

2023-04-20 10:04 UTC, H7GhosT commented on packages/user-interface/src/components/Button/Button.tsx
> +  text: string;
Guess what type you need to set for children

2023-04-20 10:04 UTC, H7GhosT commented on packages/user-interface/src/components/DeletePostModal/DeletePostModal.tsx
> +  setShowModal: (arg: boolean) => void;
For event handlers use namings like `onDelete`, `onClose`. And you don't need paramenters here

2023-04-20 10:04 UTC, H7GhosT commented on packages/user-interface/src/components/Modal/Modal.tsx
>      <div className='modal'>
Does your modal close when you click outside it?

2023-04-20 10:04 UTC, H7GhosT commented on packages/user-interface/src/components/UserCard/UserCard.tsx
> +  setShowModalEdit: (arg: boolean) => void;
Same here `onEdit`, `onDelete`....

2023-04-20 10:08 UTC, Obi1kan commented on packages/user-interface/src/components/Button/Button.tsx
> +  text: string;
> Guess what type you need to set for children

ReactNode?

2023-04-20 10:18 UTC, Obi1kan commented on packages/user-interface/src/pages/EditPost/EditPost.tsx
> +    `edit-post`,
All it's good. Do you mean that in useQuery the key is always 'edit-post'

2023-04-25 14:13 UTC, merged